apiVersion: v1
kind: Pod
spec:
  containers:
    - name: pack
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
        - name: dockerhub-creds
          mountPath: /root/.docker
          readOnly: true
      image: buildpacksio/pack:0.12.0
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
    - name: kube
      image: hferentschik/kustomize:0.0.1
      command:
        - cat
      tty: true 
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
    - name: dockerhub-creds
      secret:
        secretName: dockerhub-creds
